dbt_crypto:
  target: dev

  outputs:
    dev:
      type: postgres
      host: 
      port: 5432
      user: neondb_owner
      password: "b"
      dbname: neondb
      schema: analytics
      threads: 4
      sslmode: require
