dbt_crypto:
  target: dev

  outputs:
    dev:
      type: postgres
      host: ep-rough-water-ayj5p7ft-pooler.c-5.us-east-2.aws.neon.tech
      port: 5432
      user: neondb_owner
      password: "npg_JLTZK0t4OIgb"
      dbname: neondb
      schema: analytics
      threads: 4
      sslmode: require